# do not use "latest" here, if you want this to work in the future
image: docker:latest

services:
  - docker:18.09.7-dind

stages:
  - build
  
before_script:
  - docker version

variables:
  DOCKER_HOST: tcp://localhost:2375/

build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
