server:
  port: 9720

spring:
  h2:
    console:
      enabled: false
      path: /h2-console

datasource:
  url: jdbc:h2:mem:DB;INIT=CREATE SCHEMA POSM2V AUTHORIZATION sa;
  username: sa
  password:
  driver-class-name: org.h2.Driver