server:
  port: 9720

spring:
  h2:
    console:
      enabled: false
      path: /h2-console

datasource:
  url: jdbc:mariadb://172.25.219.61:3306/posctzn
  username: dev
  password: dbdev
  driver-class-name: org.mariadb.jdbc.Driver

