server:
  port: 9720

spring:
  h2:
    console:
      enabled: false
      path: /h2-console

datasource:
  url: jdbc:mariadb://localhost:3306/posctzn
  username: root
  password: 123456

#  url: jdbc:mariadb://localhost:3306/posctzn
#  username: root
#  password: 123456
  driver-class-name: org.mariadb.jdbc.Driver

