server:
  port: 9720

spring:
  h2:
    console:
      enabled: false
      path: /h2-console

datasource:
  url: jdbc:mariadb://localhost:3306/posctzn
  username: root
  password: 123456
  driver-class-name: org.mariadb.jdbc.Driver

minio:
  url: http://172.25.219.61:6040/
  accessKey: 2046KAWetUZYcG8nubg0
  secretKey: cpxDglli2pZI3KdiIsG1ZdJVi0wgRCFlBwQlK5OJ
  bucketName: ampro


email:
  smtpHostServer: 127.0.0.1
  smtpHostServerPort: 578
  emailId: no_reply@posco.net
  emailIdAlias: no_reply
  emailPass: abc@123
  frontEndUrl: http://localhost:3000