server:
  port: 9720

spring:
  h2:
    console:
      enabled: false
      path: /h2-console

datasource:
  url: jdbc:mariadb://localhost:3307/posctzn
  username: root
  password: dbdev
  driver-class-name: org.mariadb.jdbc.Driver

